### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by ghanavat** [cbosco/googiespell#1]
Is this project still active? Website isn't loading. The readme only contains two links which are not loading and returns 404 status code.

I am trying to use is within Roundcube and it seems like other dictionaries apart from en_GB and en_US isn't functioning correctly. Specifically fa_IR.

Thanks,
Saeed

**Comment by ghost** [comment]
Please fix the README links, they now appear to go to a Chinese online casino.

**Comment by cbosco** [comment]
Thanks, in general I would not use this in production. It hasn't been tested in any current web browsers.
